export const games = [
  {
    title: "The Evil Within 2",
    platforms: ["fab fa-playstation"],
    rating: 82,
    likes: 3894,
    image: "https://placehold.co/300x200?text=The+Evil+Within+2",
    alt: "The Evil Within 2 game cover",
  },
  {
    title: "Borderlands 3",
    platforms: ["fab fa-playstation", "fab fa-xbox", "fab fa-windows"],
    rating: 83,
    likes: 5254,
    image: "https://placehold.co/300x200?text=Borderlands+3",
    alt: "Borderlands 3 game cover",
  },
  {
    title: "Unreal Tournament 3 Black",
    platforms: ["fab fa-playstation", "fab fa-xbox"],
    rating: 83,
    likes: 2417,
    image: "https://placehold.co/300x200?text=Unreal+Tournament+3+Black",
    alt: "Unreal Tournament 3 Black game cover",
  },
  {
    title: "Gunnhildr",
    platforms: ["fab fa-windows"],
    rating: null,
    likes: 1,
    image: "https://placehold.co/300x200?text=Gunnhildr",
    alt: "Gunnhildr game cover",
  },
  {
    title: "X Rebirth",
    platforms: ["fab fa-apple"],
    rating: 33,
    likes: 485,
    image: "https://placehold.co/300x200?text=X+Rebirth",
    alt: "X Rebirth game cover",
  },
  {
    title: "Torchlight: Infinite",
    platforms: ["fab fa-apple", "fab fa-android"],
    rating: null,
    likes: 628,
    image: "https://placehold.co/300x200?text=Torchlight+Infinite",
    alt: "Torchlight: Infinite game cover",
  },
  {
    title: "Heavy Rain",
    platforms: ["fab fa-playstation"],
    rating: 80,
    likes: 7633,
    image: "https://placehold.co/300x200?text=Heavy+Rain",
    alt: "Heavy Rain game cover",
  },
  {
    title: "Assassin's Creed Rogue",
    platforms: ["fab fa-playstation", "fab fa-xbox", "fab fa-windows"],
    rating: 74,
    likes: 2772,
    image: "https://placehold.co/300x200?text=Assassin's+Creed+Rogue",
    alt: "Assassin's Creed Rogue game cover",
  },
];
